name: Penguin_Plugin_1
main: Minecraft.nukkit.cn.shygard.nukkit.testPlugin.Main_PluginBase
version: 0. 0. 3
api: [1.0.9]

author:  penguin
website: xxx

commands:
  biomes:
    permission: "command.biomes"
    description: "群系测试"
    usage: "/biomes id"

  get:
    permission: "command.NewPlayerJoin.Gift"
    description: "获取新人大礼包"
    usage: "/get [gift]"

  do:
    permission: "command.do"
    description: "测试"
    usage: "/do"

  zoom:
    permission: "command.Model.Zoom"
    description: "自由缩放玩家大小,需要输入全名,若卡顿请变回1倍初始状态！"
    usage: "/zoom [name] [size]"

  fill:
    permission: "command.fill"
    description: "改版fill--只需要一个坐标--填充这个坐标到你脚的区域--方块是数字类型，输入/block查询当前手上的方块]"
    usage: "/fill x y z [Block]"

  clear:
    permission: "command.clear"
    description: "清空玩家（自己或别人）背包"
    usage: "/clear  清理自己背包   /clear [name] 清理指定玩家背包"

  ping:
    permission: "command.ping"
    description: "检测延迟"
    usage: "/ping"

  achievement:
    permission: "command.achievement"
    description: "成就(+数据库)控制指令"
    usage: "/achievement clear|add|remove"

  set:
    permission: "WoodAxe.set"
    description: "放置方块----小破斧造大世界"
    usage: "/set [Block ID]"

  round:
    permission: "Set.round"
    description: "画圆指令,输入/round查看用法"
    usage: "画圆指令用法：/round 半径(整数，必选) 方块ID(必选) 方块特殊值（可选）keep(保持，可选，使用时，方块特殊值必须要写)"

  ball:
    permission: "Set.ball"
    description: "画球指令，输入/ball查看用法"
    usage: "画球指令用法：/ball 半径(整数，必选) 方块ID(必选) 方块特殊值（可选）keep(保持，可选，使用时，方块特殊值必须要写)"

permissions:
  command.biomes:
    default: op

  Set.ball:
    default: op

  Set.round:
    default: op

  WoodAxe.set:
    default: op

  command.do:
    default: op

  command.fill:
    default: op

  command.clear:
    default: op

  command.ping:
    default: true

  command.achievement:
    default: op

  command.NewPlayerJoin.Gift:
    default: true

  command.Model.Zoom:
    default: op



#.....